"""initial schema: the six tables

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 23:15:23.198657
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('host_pin_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('songs',
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('track', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('original_key', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('lyrics_source', sa.String(length=20), nullable=True),
    sa.Column('alignment_confidence', sa.Float(), nullable=True),
    sa.Column('pipeline_version', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_reason', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('guests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guests_room_id'), ['room_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['songs.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_one_active', ['video_id', 'kind'], unique=True, sqlite_where=sa.text("status IN ('pending', 'running')"))
        batch_op.create_index(batch_op.f('ix_jobs_video_id'), ['video_id'], unique=False)

    op.create_table('song_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('guest_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['songs.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_events_video_id'), ['video_id'], unique=False)

    op.create_table('queue_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('guest_id', sa.String(length=36), nullable=True),
    sa.Column('singer_name', sa.String(length=40), nullable=True),
    sa.Column('semitones', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('removed_reason', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['songs.video_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_entries_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_entries_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_entries_video_id'))
        batch_op.drop_index(batch_op.f('ix_queue_entries_room_id'))

    op.drop_table('queue_entries')
    with op.batch_alter_table('song_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_events_video_id'))

    op.drop_table('song_events')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_video_id'))
        batch_op.drop_index('ix_jobs_one_active', sqlite_where=sa.text("status IN ('pending', 'running')"))

    op.drop_table('jobs')
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guests_room_id'))

    op.drop_table('guests')
    op.drop_table('songs')
    op.drop_table('rooms')
    # ### end Alembic commands ###
